//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace administraClima.SRClima {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tlbusuario", Namespace="http://schemas.datacontract.org/2004/07/WS_controlClima.modelo", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class tlbusuario : administraClima.SRClima.EntityObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string contraseñaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ideusuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usuarioField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string contraseña {
            get {
                return this.contraseñaField;
            }
            set {
                if ((object.ReferenceEquals(this.contraseñaField, value) != true)) {
                    this.contraseñaField = value;
                    this.RaisePropertyChanged("contraseña");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ideusuario {
            get {
                return this.ideusuarioField;
            }
            set {
                if ((this.ideusuarioField.Equals(value) != true)) {
                    this.ideusuarioField = value;
                    this.RaisePropertyChanged("ideusuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string usuario {
            get {
                return this.usuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.usuarioField, value) != true)) {
                    this.usuarioField = value;
                    this.RaisePropertyChanged("usuario");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StructuralObject", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses", IsReference=true)]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(administraClima.SRClima.EntityObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(administraClima.SRClima.tblzona))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(administraClima.SRClima.tblclima))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(administraClima.SRClima.tlbusuario))]
    public partial class StructuralObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityObject", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses", IsReference=true)]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(administraClima.SRClima.tblzona))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(administraClima.SRClima.tblclima))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(administraClima.SRClima.tlbusuario))]
    public partial class EntityObject : administraClima.SRClima.StructuralObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private administraClima.SRClima.EntityKey EntityKeyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public administraClima.SRClima.EntityKey EntityKey {
            get {
                return this.EntityKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityKeyField, value) != true)) {
                    this.EntityKeyField = value;
                    this.RaisePropertyChanged("EntityKey");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tblzona", Namespace="http://schemas.datacontract.org/2004/07/WS_controlClima.modelo", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class tblzona : administraClima.SRClima.EntityObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idezonaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string zonaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idezona {
            get {
                return this.idezonaField;
            }
            set {
                if ((this.idezonaField.Equals(value) != true)) {
                    this.idezonaField = value;
                    this.RaisePropertyChanged("idezona");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string zona {
            get {
                return this.zonaField;
            }
            set {
                if ((object.ReferenceEquals(this.zonaField, value) != true)) {
                    this.zonaField = value;
                    this.RaisePropertyChanged("zona");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tblclima", Namespace="http://schemas.datacontract.org/2004/07/WS_controlClima.modelo", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class tblclima : administraClima.SRClima.EntityObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fechayhoraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ideclimaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idezonaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string presipitacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string temperaturaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vientoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fechayhora {
            get {
                return this.fechayhoraField;
            }
            set {
                if ((this.fechayhoraField.Equals(value) != true)) {
                    this.fechayhoraField = value;
                    this.RaisePropertyChanged("fechayhora");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ideclima {
            get {
                return this.ideclimaField;
            }
            set {
                if ((this.ideclimaField.Equals(value) != true)) {
                    this.ideclimaField = value;
                    this.RaisePropertyChanged("ideclima");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idezona {
            get {
                return this.idezonaField;
            }
            set {
                if ((this.idezonaField.Equals(value) != true)) {
                    this.idezonaField = value;
                    this.RaisePropertyChanged("idezona");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string presipitacion {
            get {
                return this.presipitacionField;
            }
            set {
                if ((object.ReferenceEquals(this.presipitacionField, value) != true)) {
                    this.presipitacionField = value;
                    this.RaisePropertyChanged("presipitacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string temperatura {
            get {
                return this.temperaturaField;
            }
            set {
                if ((object.ReferenceEquals(this.temperaturaField, value) != true)) {
                    this.temperaturaField = value;
                    this.RaisePropertyChanged("temperatura");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string viento {
            get {
                return this.vientoField;
            }
            set {
                if ((object.ReferenceEquals(this.vientoField, value) != true)) {
                    this.vientoField = value;
                    this.RaisePropertyChanged("viento");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityKey", Namespace="http://schemas.datacontract.org/2004/07/System.Data", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class EntityKey : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EntityContainerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private administraClima.SRClima.EntityKeyMember[] EntityKeyValuesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EntitySetNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EntityContainerName {
            get {
                return this.EntityContainerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityContainerNameField, value) != true)) {
                    this.EntityContainerNameField = value;
                    this.RaisePropertyChanged("EntityContainerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public administraClima.SRClima.EntityKeyMember[] EntityKeyValues {
            get {
                return this.EntityKeyValuesField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityKeyValuesField, value) != true)) {
                    this.EntityKeyValuesField = value;
                    this.RaisePropertyChanged("EntityKeyValues");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EntitySetName {
            get {
                return this.EntitySetNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EntitySetNameField, value) != true)) {
                    this.EntitySetNameField = value;
                    this.RaisePropertyChanged("EntitySetName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityKeyMember", Namespace="http://schemas.datacontract.org/2004/07/System.Data")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(administraClima.SRClima.EntityObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(administraClima.SRClima.StructuralObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(administraClima.SRClima.EntityKey))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(administraClima.SRClima.EntityKeyMember[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(administraClima.SRClima.tlbusuario[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(administraClima.SRClima.tlbusuario))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(administraClima.SRClima.tblzona[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(administraClima.SRClima.tblzona))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(administraClima.SRClima.tblclima[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(administraClima.SRClima.tblclima))]
    public partial class EntityKeyMember : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key {
            get {
                return this.KeyField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyField, value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SRClima.IClimaService")]
    public interface IClimaService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClimaService/agregarUsuario", ReplyAction="http://tempuri.org/IClimaService/agregarUsuarioResponse")]
        string agregarUsuario(string usuario, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClimaService/login", ReplyAction="http://tempuri.org/IClimaService/loginResponse")]
        bool login(string user, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClimaService/actualizarUsuario", ReplyAction="http://tempuri.org/IClimaService/actualizarUsuarioResponse")]
        string actualizarUsuario(int ideusuario, string usuario, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClimaService/eliminarUsuario", ReplyAction="http://tempuri.org/IClimaService/eliminarUsuarioResponse")]
        string eliminarUsuario(int ideusuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClimaService/listarUsuario", ReplyAction="http://tempuri.org/IClimaService/listarUsuarioResponse")]
        administraClima.SRClima.tlbusuario[] listarUsuario();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClimaService/agregarZona", ReplyAction="http://tempuri.org/IClimaService/agregarZonaResponse")]
        string agregarZona(string zona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClimaService/actualizarZona", ReplyAction="http://tempuri.org/IClimaService/actualizarZonaResponse")]
        string actualizarZona(int idezona, string zona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClimaService/eliminarZona", ReplyAction="http://tempuri.org/IClimaService/eliminarZonaResponse")]
        string eliminarZona(int idezon);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClimaService/listarZonas", ReplyAction="http://tempuri.org/IClimaService/listarZonasResponse")]
        administraClima.SRClima.tblzona[] listarZonas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClimaService/agregarClima", ReplyAction="http://tempuri.org/IClimaService/agregarClimaResponse")]
        string agregarClima(int idezona, System.DateTime fechahora, string temperatura, string presipitacion, string viento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClimaService/actualizarClima", ReplyAction="http://tempuri.org/IClimaService/actualizarClimaResponse")]
        string actualizarClima(int ideclima, int idezona, System.DateTime fechahora, string temperatura, string presipitacion, string viento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClimaService/eliminarClima", ReplyAction="http://tempuri.org/IClimaService/eliminarClimaResponse")]
        string eliminarClima(int ideclima);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClimaService/listarClimas", ReplyAction="http://tempuri.org/IClimaService/listarClimasResponse")]
        administraClima.SRClima.tblclima[] listarClimas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClimaService/listarClimasPorZona", ReplyAction="http://tempuri.org/IClimaService/listarClimasPorZonaResponse")]
        administraClima.SRClima.tblclima[] listarClimasPorZona(int idezona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClimaService/verClima", ReplyAction="http://tempuri.org/IClimaService/verClimaResponse")]
        administraClima.SRClima.tblclima[] verClima(int idezona, System.DateTime fechahora);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IClimaServiceChannel : administraClima.SRClima.IClimaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClimaServiceClient : System.ServiceModel.ClientBase<administraClima.SRClima.IClimaService>, administraClima.SRClima.IClimaService {
        
        public ClimaServiceClient() {
        }
        
        public ClimaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClimaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClimaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClimaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string agregarUsuario(string usuario, string password) {
            return base.Channel.agregarUsuario(usuario, password);
        }
        
        public bool login(string user, string pass) {
            return base.Channel.login(user, pass);
        }
        
        public string actualizarUsuario(int ideusuario, string usuario, string password) {
            return base.Channel.actualizarUsuario(ideusuario, usuario, password);
        }
        
        public string eliminarUsuario(int ideusuario) {
            return base.Channel.eliminarUsuario(ideusuario);
        }
        
        public administraClima.SRClima.tlbusuario[] listarUsuario() {
            return base.Channel.listarUsuario();
        }
        
        public string agregarZona(string zona) {
            return base.Channel.agregarZona(zona);
        }
        
        public string actualizarZona(int idezona, string zona) {
            return base.Channel.actualizarZona(idezona, zona);
        }
        
        public string eliminarZona(int idezon) {
            return base.Channel.eliminarZona(idezon);
        }
        
        public administraClima.SRClima.tblzona[] listarZonas() {
            return base.Channel.listarZonas();
        }
        
        public string agregarClima(int idezona, System.DateTime fechahora, string temperatura, string presipitacion, string viento) {
            return base.Channel.agregarClima(idezona, fechahora, temperatura, presipitacion, viento);
        }
        
        public string actualizarClima(int ideclima, int idezona, System.DateTime fechahora, string temperatura, string presipitacion, string viento) {
            return base.Channel.actualizarClima(ideclima, idezona, fechahora, temperatura, presipitacion, viento);
        }
        
        public string eliminarClima(int ideclima) {
            return base.Channel.eliminarClima(ideclima);
        }
        
        public administraClima.SRClima.tblclima[] listarClimas() {
            return base.Channel.listarClimas();
        }
        
        public administraClima.SRClima.tblclima[] listarClimasPorZona(int idezona) {
            return base.Channel.listarClimasPorZona(idezona);
        }
        
        public administraClima.SRClima.tblclima[] verClima(int idezona, System.DateTime fechahora) {
            return base.Channel.verClima(idezona, fechahora);
        }
    }
}
